# https://taskfile.dev

version: "3"
dotenv:
  - .env

tasks:
  default:
    desc: Run on connected iOS device by default
    deps: [ device ]

  device:
    desc: Build, install, and run on connected iOS device
    cmds:
      - IOS_TARGETS=aarch64-apple-ios
        xcodebuild
        -scheme bevister
        -configuration Debug
        -derivedDataPath build
        -destination 'generic/platform=iOS'
        DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"
        CODE_SIGN_STYLE="${CODE_SIGN_STYLE:-Automatic}"
        CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY:-Apple Development}"
        PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER"
        -allowProvisioningUpdates
        -allowProvisioningDeviceRegistration &&
        bash ./ios-src/open_xcode_and_build.sh

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -r build || true
      - cargo clean
