[package]
name = "voxel_demo_app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["dynamic_linking"] }
avian3d = { workspace = true }
bevy-tnua = { workspace = true }
bevy-tnua-avian3d = { workspace = true }
bevy_enhanced_input = { workspace = true }
bevy_hanabi = { workspace = true }
bevy_voxel_plugin = { path = "../bevy_voxel_plugin" }
bevy_egui = { workspace = true }
bevy_prng = { workspace = true }
bevy_rand = { workspace = true }
rand = { workspace = true }
iyes_perf_ui = { workspace = true }
tracing = { workspace = true }
