[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

# Use LLVM instead of Cranelift for targets that require it (selected via --profile dev-llvm)
[profile.dev-llvm]
inherits = "dev"
codegen-backend = "llvm"

[profile.dev.package."*"]
codegen-backend = "llvm"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
]
